-- Insert fields of study
INSERT INTO public.fields_of_study (id, name_ru, name_kz, name_en, icon) VALUES
('it', 'IT и программирование', 'IT және бағдарламалау', 'IT & Programming', 'Monitor'),
('medicine', 'Медицина', 'Медицина', 'Medicine', 'Heart'),
('law', 'Право', 'Құқық', 'Law', 'Scale'),
('economics', 'Экономика и бизнес', 'Экономика және бизнес', 'Economics & Business', 'TrendingUp'),
('engineering', 'Инженерия', 'Инженерия', 'Engineering', 'Cog'),
('humanities', 'Гуманитарные науки', 'Гуманитарлық ғылымдар', 'Humanities', 'BookOpen'),
('natural', 'Естественные науки', 'Жаратылыстану ғылымдары', 'Natural Sciences', 'Leaf'),
('arts', 'Искусство и дизайн', 'Өнер және дизайн', 'Arts & Design', 'Palette')
ON CONFLICT (id) DO NOTHING;

-- Insert universities
INSERT INTO public.universities (id, name_ru, name_kz, name_en, description_ru, description_kz, description_en, type, founded_year, region, city, address, website, email, phone, logo_url, cover_image_url, ranking_national, ranking_qs, students_count, teachers_count, has_grants, has_dormitory, has_military_department, mission_ru, mission_kz, mission_en) VALUES
(gen_random_uuid(), 'Казахский национальный университет им. аль-Фараби', 'Әл-Фараби атындағы Қазақ ұлттық университеті', 'Al-Farabi Kazakh National University', 'Ведущий национальный университет Казахстана, основанный в 1934 году. Крупнейший научно-образовательный центр страны.', 'Қазақстанның жетекші ұлттық университеті, 1934 жылы құрылған. Елдің ең ірі ғылыми-білім беру орталығы.', 'Leading national university of Kazakhstan, founded in 1934. The largest scientific and educational center of the country.', 'national', 1934, 'Алматы', 'Алматы', 'пр. аль-Фараби, 71', 'https://www.kaznu.kz', 'info@kaznu.kz', '+7 (727) 377-33-33', 'https://www.kaznu.kz/content/images/pages/logo.png', 'https://images.unsplash.com/photo-1562774053-701939374585?w=1200', 1, 150, 25000, 2500, true, true, true, 'Подготовка высококвалифицированных специалистов, способных внести вклад в устойчивое развитие Казахстана и мирового сообщества.', 'Қазақстан мен әлемдік қоғамдастықтың тұрақты дамуына үлес қоса алатын жоғары білікті мамандар даярлау.', 'Training highly qualified specialists capable of contributing to the sustainable development of Kazakhstan and the world community.'),

(gen_random_uuid(), 'Назарбаев Университет', 'Назарбаев Университеті', 'Nazarbayev University', 'Автономный исследовательский университет, основанный в 2010 году. Партнерство с ведущими мировыми университетами.', 'Автономды зерттеу университеті, 2010 жылы құрылған. Әлемнің жетекші университеттерімен серіктестік.', 'Autonomous research university founded in 2010. Partnership with leading world universities.', 'international', 2010, 'Астана', 'Астана', 'ул. Кабанбай батыра, 53', 'https://nu.edu.kz', 'admissions@nu.edu.kz', '+7 (7172) 70-66-88', 'https://nu.edu.kz/wp-content/themes/developer/images/logo.svg', 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=1200', 2, 100, 8000, 1200, true, true, false, 'Создание передового образовательного и исследовательского центра мирового уровня в Казахстане.', 'Қазақстанда әлемдік деңгейдегі озық білім беру және зерттеу орталығын құру.', 'Creating a world-class advanced educational and research center in Kazakhstan.'),

(gen_random_uuid(), 'Казахстанско-Британский технический университет', 'Қазақстан-Британ техникалық университеті', 'Kazakh-British Technical University', 'Ведущий технический университет с британскими стандартами образования.', 'Британ білім беру стандарттары бар жетекші техникалық университет.', 'Leading technical university with British education standards.', 'private', 2001, 'Алматы', 'Алматы', 'ул. Толе би, 59', 'https://kbtu.edu.kz', 'info@kbtu.kz', '+7 (727) 291-58-95', 'https://upload.wikimedia.org/wikipedia/commons/d/dc/KBTU_Logo.png', 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200', 3, 250, 5000, 800, true, true, false, 'Подготовка специалистов мирового класса в сфере технологий и бизнеса.', 'Технология және бизнес саласында әлемдік деңгейдегі мамандар даярлау.', 'Training world-class specialists in technology and business.'),

(gen_random_uuid(), 'Евразийский национальный университет им. Л.Н. Гумилёва', 'Л.Н. Гумилев атындағы Еуразия ұлттық университеті', 'L.N. Gumilyov Eurasian National University', 'Крупнейший университет столицы, многопрофильный образовательный центр.', 'Астананың ең ірі университеті, көпсалалы білім беру орталығы.', 'The largest university in the capital, a multidisciplinary educational center.', 'national', 1996, 'Астана', 'Астана', 'ул. Сатпаева, 2', 'https://enu.kz', 'info@enu.kz', '+7 (7172) 35-09-09', 'https://enu.kz/images/logo.png', 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=1200', 4, 350, 20000, 2000, true, true, true, 'Формирование интеллектуальной элиты нации через качественное образование и науку.', 'Сапалы білім мен ғылым арқылы ұлттың зияткерлік элитасын қалыптастыру.', 'Forming the intellectual elite of the nation through quality education and science.'),

(gen_random_uuid(), 'Международный университет информационных технологий', 'Халықаралық ақпараттық технологиялар университеті', 'International IT University', 'Специализированный IT-университет с фокусом на современные технологии и стартапы.', 'Заманауи технологиялар мен стартаптарға бағытталған мамандандырылған IT-университет.', 'Specialized IT university focused on modern technologies and startups.', 'private', 2009, 'Алматы', 'Алматы', 'ул. Манаса, 34/1', 'https://iitu.edu.kz', 'info@iitu.edu.kz', '+7 (727) 330-85-85', 'https://iitu.edu.kz/logo.png', 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200', 8, NULL, 4000, 400, true, false, false, 'Создание IT-специалистов нового поколения для цифровой экономики Казахстана.', 'Қазақстанның цифрлық экономикасы үшін жаңа буын IT-мамандарын даярлау.', 'Creating a new generation of IT specialists for the digital economy of Kazakhstan.'),

(gen_random_uuid(), 'Казахский национальный медицинский университет им. С.Д. Асфендиярова', 'С.Ж. Асфендияров атындағы Қазақ ұлттық медицина университеті', 'Asfendiyarov Kazakh National Medical University', 'Ведущий медицинский университет Казахстана с 90-летней историей.', '90 жылдық тарихы бар Қазақстанның жетекші медицина университеті.', 'Leading medical university of Kazakhstan with 90 years of history.', 'national', 1931, 'Алматы', 'Алматы', 'ул. Толе би, 94', 'https://kaznmu.kz', 'info@kaznmu.kz', '+7 (727) 292-79-37', 'https://kaznmu.kz/logo.png', 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=1200', 5, NULL, 12000, 1500, true, true, false, 'Подготовка врачей мирового уровня для здоровья нации.', 'Ұлт денсаулығы үшін әлемдік деңгейдегі дәрігерлер даярлау.', 'Training world-class doctors for the health of the nation.');